### ISSUE TITLE
Can the earthshaper's tectonic slam cast in Ruby Life Pools have a better alert than "watch your step"?

### ISSUE THREAD

**Issue by gotex007** [DeadlyBossMods/DBM-Dungeons#108]
DBM calls out "watch your step" when the earthshaper starts its tectonic slam cast. The mechanic is actually to CC the mob to stop its uninterruptible cast or it does party-wide damage. Can a different/better voice alert be used there? [The description in DBM](https://i.imgur.com/8VL9li0.png) isn't accurate either as it's not a normally dodge-able ability.

**Comment by gotex007** [comment]
Well now it doesn't have any voice alert.

**Comment by MysticalOS** [comment]
it's tricky to have an alert specifically for disruptions/ccs cause it's not an interrupt. what if group doesn't have a crowd control? then they'll feel like the alert is nagging them to do something that's undoable
it's a 4 second cast and it does have a cast warning (no voice that's true) but those that know they can stop it should still see it. I may revisit it more if the spec role table in DBM ever gets updating but that's difficult since I don't know most classes well enough to fill in every single class spec and talent that can stun, dispel, etc. it's why default settings have been very inaccurate in DBM in dragonflight too. it's basically using pre DF tables for most classes.

not saying i won't improve this, but may not be right away cause other stuff needs to be done.

**Comment by MysticalOS** [comment]
I went ahead and improved most of the big CC alerts with crowd control voice alert.
