### ISSUE TITLE
DMB not skipping skipping in-game cinematics

### ISSUE THREAD

**Issue by Luniz2k1** [DeadlyBossMods/DBM-Dungeons#173]
**Describe the bug**
Cinematic skips not skipping

**Do you have an error log of what happened?**
no

**To Reproduce**
Do something that shows a cinematic

**Screenshots**
No

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of DeadlyBossMods are you using?**
Latest (r119)

**Was it working in a previous version? If yes, which was the last good one?**
Unsure.  Started on 2024-02/05

**Additional context**
None

**Comment by MysticalOS** [comment]
Which cinematics?
Only one that broke recently is the fyrakk intro one. rest should remain blocked, after they've played at least once.

**Comment by Luniz2k1** [comment]
Seige of Orgrimmar are not skipping, same with last boss in Doti Fall

**Comment by MysticalOS** [comment]
there have been no changes to those. But default options reset, so you may have to see them all once first (per default options) and they'll be skipped second time.

**Comment by Luniz2k1** [comment]
![DBM](https://github.com/DeadlyBossMods/DBM-Dungeons/assets/16273612/6d8bf341-8ef6-407a-b899-2760a378afba)

**Comment by MysticalOS** [comment]
Uncheck last option and see if they skip. or see if they skip the SECOND time you do it.

I fixed a potential bug where it is wiping the "already seen" cache which may be causing every view to be treated as first view. However this is not a new bug, so if you were previously using "after seen at least once" you would have had same bug you are having now. if you had it set to "always block" before, then to emulate that behavior again uncheck last box.

**Comment by Luniz2k1** [comment]
Will try Garrosh again and see if it shows the cinematic...

**Comment by MysticalOS** [comment]
First scene might be "per character" so that may be an unscientific method to test it btw. It'd still just flag the first seen and block it next time.

perhaps i'm just not being clear how that option actually work and I don't know what you had it set to before the update. 

before update it was a less clear drop down that basically said "always, after once, or never" and most had it set to "always" and NOT "after once". the new default is now "after once" but it was broken down from a less clear dropdown to more clear checkboxes (or at least I thought they were more clear, maybe not).

The screen shot you showed shows you're using the new defaults of "blocking all, but only after seeing EACH MOVIE once" so your experience, as expected, is that they played first time you encountered them (and they'd block NEXT time).

Now it'll be a bug if you do it again and still see it. which is entirely possible cause i did just fix a case this may happen. But i also want to be clear if you do not want it to play cinematics once before blocking, UNCHECK 3rd option.

**Comment by Luniz2k1** [comment]
I unchecked the 3rd option after you commented and the cutscenes skipped.
