### ISSUE TITLE
Azureblade: Turn on countdown for Ancient Orb by default

### ISSUE THREAD

**Issue by Aziroshin** [DeadlyBossMods/DBM-Dungeons#99]
**Is your feature request related to a problem? Please describe.**
A lot of people seem to miss the Ancient Orb and die, just like I did before I went to the settings and made it count down using the `SA 2` voice. I reckon most people won't do that. It is my hypothesis that making that a default setting would noticeably improve the average quality of Azure Vault runs, especially in PUGs.

**Describe the solution you'd like**
Make it so the "special announce" for `Ancient Orb` is set to a voiced countdown by default.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by MysticalOS** [comment]
I'm still iffy on this because generally users complained when countdowns were on by default for specific encounter spells. users are able to enable it on anything they choose.
I think about only thing countdown is on by default for this entire season is thundering.

I won't close issue but was kinda hoping to get more feedback on it.
